"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, CheckCheck, Clock3, MessageSquare, Plus, Search } from "lucide-react";
import { api, post, dateLabel, stepLabel, stepIndex, type Workflow, type Application } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { CompanyMark, Empty, ErrorNotice, Loading, PageHeading, StatusBadge } from "@/components/shared";

function useOverview() {
  const [flows,setFlows]=useState<Workflow[]>([]);const [apps,setApps]=useState<{submitted:Application[];saved:Application[]}>({submitted:[],saved:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{Promise.all([api<Workflow[]>("/workflows"),api<typeof apps>("/applications")]).then(([flows,apps])=>{setFlows(flows);setApps(apps);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  return {flows:flows.filter(flow=>flow.step!=="submitted"),apps,loading,error,setError};
}
function FlowRow({flow}: {flow:Workflow}) {return <Link href={`/workflow/${flow.id}`} className="flex items-center gap-4 border-b px-6 py-5 last:border-0 hover:bg-muted/70"><CompanyMark name={flow.selected_job?.company || flow.search.query}/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-medium">{flow.selected_job?.title || flow.search.query}</h3><p className="mt-1 text-xs text-muted-foreground">{flow.selected_job?.company || flow.search.location} <span className="mx-1">·</span> {dateLabel(flow.updated_at)}</p></div><div className="hidden min-w-32 sm:block"><p className="mb-2 text-[11px] text-muted-foreground">{flow.status === "running" ? "Processing…" : flow.status === "error" ? "Needs attention" : stepLabel(flow.step)}</p><div className="flex gap-1">{Array.from({length:5},(_,i)=><span className={`h-1 w-5 rounded-full ${i <= stepIndex(flow.step) ? "bg-primary/70" : "bg-muted"}`} key={i}/>)}</div></div><ArrowRight size={15} className="ml-2 text-muted-foreground"/></Link>;}

export function Dashboard() {
  const {flows,apps,loading,error}=useOverview();
  const interview=apps.submitted.filter(app=>app.status === "interview").length;
  const cards=[{label:"In progress",value:flows.length,icon:Clock3,description:"Your next moves",href:"/applications"},{label:"Applications sent",value:apps.submitted.length,icon:BriefcaseBusiness,description:"Opportunities pursued",href:"/tracker"},{label:"Interviews",value:interview,icon:MessageSquare,description:"Conversations ahead",href:"/tracker?status=interview"},{label:"Offers",value:apps.submitted.filter(a=>a.status === "offer").length,icon:CheckCheck,description:"New possibilities",href:"/tracker?status=offer"}];
  return <div className="fade-in"><PageHeading eyebrow="Your career, with intention" title="Welcome to your next chapter." description="A little focus today. A new opportunity tomorrow."><Button asChild><Link href="/workflow"><Plus/>New application</Link></Button></PageHeading><ErrorNotice message={error}/>{loading ? <Loading/> : <><div className="mb-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=><Link href={card.href} key={card.label}><Card className="p-5 transition-colors hover:border-primary/30"><div className="flex items-center justify-between text-xs text-muted-foreground">{card.label}<card.icon size={16}/></div><p className="mb-2 mt-5 text-3xl font-semibold tracking-tight">{card.value}</p><p className="text-[11px] text-muted-foreground">{card.description}</p></Card></Link>)}</div><div className="mb-8 flex flex-wrap items-center justify-between gap-6 rounded-xl border border-primary/10 bg-[#f7f5fc] p-7"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-primary">One clear workflow</p><h2 className="text-lg font-semibold tracking-tight">From a promising role to a thoughtful application.</h2><p className="mt-2 text-xs text-muted-foreground">Search, tailor, review, and send. Every step in one place.</p></div><Button asChild variant="outline" className="bg-white"><Link href="/workflow">Find an opportunity<ArrowUpRight/></Link></Button></div><div className="grid gap-7 xl:grid-cols-[1.2fr_1fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b px-6 py-5"><h2 className="text-sm font-semibold">Pick up where you left off</h2><Link href="/applications" className="text-xs text-primary">View all</Link></div>{flows.length ? flows.slice(0,4).map(flow=><FlowRow flow={flow} key={flow.id}/>) : <Empty title="Room for your next move" description="Your unfinished applications will be saved here, ready when you are."/>}</Card><Card className="overflow-hidden"><div className="flex items-center justify-between border-b px-6 py-5"><h2 className="text-sm font-semibold">Recent applications</h2><Link href="/tracker" className="text-xs text-primary">View tracker</Link></div>{apps.submitted.length ? apps.submitted.slice(0,4).map(app=><Link key={app.id} href={`/tracker?application=${app.id}`} className="flex items-center gap-3 border-b p-5 last:border-0 hover:bg-muted/50"><CompanyMark name={app.company}/><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{app.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{app.company}</p></div><StatusBadge status={app.status}/></Link>) : <Empty title="Your journey, tracked" description="Submitted applications and recruiter responses will appear here." action={false}/>}</Card></div></>}</div>;
}

export function ApplicationsScreen() {
  const {flows,apps,loading,error,setError}=useOverview();const [query,setQuery]=useState("");const [busy,setBusy]=useState<number|null>(null);const router=useRouter();
  const filtered=flows.filter(flow=>`${flow.search.query} ${flow.selected_job?.company || ""} ${flow.selected_job?.title || ""}`.toLowerCase().includes(query.toLowerCase()));
  const linked=new Set(flows.map(flow=>flow.selected_job?.url));const saved=apps.saved.filter(app=>!linked.has(app.job_url) && `${app.title} ${app.company}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="fade-in"><PageHeading title="Applications" description="Work in progress, saved exactly where you left it."><Button asChild><Link href="/workflow"><Plus/>New application</Link></Button></PageHeading><ErrorNotice message={error}/><div className="relative mb-6 max-w-sm"><Search size={15} className="absolute left-3 top-3 text-muted-foreground"/><Input aria-label="Search unfinished applications" className="pl-9" placeholder="Search applications…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading ? <Loading/> : <><Card className="overflow-hidden"><div className="border-b px-6 py-4 text-xs font-medium">In progress <span className="ml-2 rounded bg-muted px-2 py-0.5 text-muted-foreground">{filtered.length}</span></div>{filtered.length ? filtered.map(flow=><FlowRow key={flow.id} flow={flow}/>) : <Empty title={query ? "No applications found" : "Start something promising"} description={query ? "Try a different role or company name." : "Each workflow is saved automatically, including your CV changes and email edits."} action={!query}/>}</Card>{saved.length > 0 && <div className="mt-9"><h2 className="text-sm font-semibold">Saved opportunities</h2><p className="mb-4 mt-1.5 text-xs text-muted-foreground">Roles from your existing CareerAI workspace. Continue a prepared application or start tailoring.</p><Card>{saved.slice(0,30).map(app=><div className="flex items-center gap-3 border-b p-5 last:border-0" key={app.id}><CompanyMark name={app.company}/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-medium">{app.title}</h3><p className="mt-1 text-xs text-muted-foreground">{app.company} · {app.location || app.source}</p></div><Button variant="outline" size="sm" disabled={busy!==null} onClick={async()=>{setBusy(app.id);try{const flow=await post<Workflow>(`/applications/${app.id}/continue`);router.push(`/workflow/${flow.id}`);}catch(e){setError((e as Error).message);setBusy(null);}}}>{busy===app.id ? "Opening…" : "Continue"}<ArrowRight/></Button></div>)}</Card></div>}</>}</div>;
}
