"use client";
import { useEffect, useState } from "react";
import { Check, FileText, Mail, Save, Upload, UserRound } from "lucide-react";
import { api, post, put, type Profile, type Settings } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ErrorNotice, Loading, PageHeading } from "@/components/shared";

export function SettingsScreen() {
  const [data,setData]=useState<Settings|null>(null);const [profile,setProfile]=useState<Profile|null>(null);const [source,setSource]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{api<Settings>("/settings").then(value=>{setData(value);setProfile(value.profile);setSource(value.cv_source);}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!data?.gmail_connecting)return;const timer=setInterval(()=>{api<Settings>("/settings").then(value=>{setData(previous=>previous ? {...previous,gmail_saved:value.gmail_saved,gmail_connecting:value.gmail_connecting,gmail_error:value.gmail_error} : value);}).catch(e=>setError(e.message));},3000);return ()=>clearInterval(timer);},[data?.gmail_connecting]);
  async function save(fn:()=>Promise<unknown>,message:string) {setBusy(true);setError("");setNotice("");try{await fn();setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!data || !profile)return <><ErrorNotice message={error}/>{!error && <Loading/>}</>;
  return <div className="fade-in max-w-4xl"><PageHeading title="Settings" description="Your experience, preferences, and connections. All in one place."/><ErrorNotice message={error || data.gmail_error}/>{notice && <p role="status" className="mb-5 flex items-center gap-2 rounded-lg bg-green-50 p-3 text-xs text-green-700"><Check size={14}/>{notice}</p>}<div className="space-y-6"><Card className="p-6"><h2 className="mb-1 flex items-center gap-2 text-sm font-semibold"><UserRound size={16} className="text-primary"/>Your profile</h2><p className="mb-6 text-xs text-muted-foreground">Used by the existing matching and tailoring services. Changes apply to new workflows.</p><form onSubmit={e=>{e.preventDefault();void save(()=>put("/settings/profile",profile),"Profile saved.");}}><div className="grid gap-5 sm:grid-cols-2"><ListField label="Target roles" values={profile.target_roles} onChange={values=>setProfile({...profile,target_roles:values})}/><ListField label="Preferred locations" values={profile.preferred_locations} onChange={values=>setProfile({...profile,preferred_locations:values})}/><div className="sm:col-span-2"><ListField label="Skills" values={profile.skills} onChange={values=>setProfile({...profile,skills:values})}/></div><label className="text-xs font-medium sm:col-span-2">Education<Input className="mt-2" value={profile.education || ""} onChange={e=>setProfile({...profile,education:e.target.value})}/></label><label className="text-xs font-medium sm:col-span-2">Experience <span className="font-normal text-muted-foreground">(one item per line)</span><Textarea className="mt-2 min-h-32" value={profile.experience.join("\n")} onChange={e=>setProfile({...profile,experience:e.target.value.split("\n")})}/></label></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={profile.remote} onChange={e=>setProfile({...profile,remote:e.target.checked})}/>Open to remote roles</label><Button type="submit" disabled={busy}><Save/>Save profile</Button></div></form></Card>
    <Card className="p-6"><h2 className="flex items-center gap-2 text-sm font-semibold"><FileText size={16} className="text-primary"/>Original CV</h2><p className="mb-5 mt-2 text-xs leading-6 text-muted-foreground">Your existing tailoring service uses a LaTeX CV. Upload a .tex file or edit the source below. Each new workflow keeps its own copy.</p><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed bg-muted/50 p-5 text-xs text-muted-foreground"><Upload size={16}/><span>Choose a LaTeX CV</span><input type="file" className="max-w-48 text-xs" accept=".tex" aria-label="Upload original CV" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>250000){setError("CV source must be smaller than 250 KB.");return;}setSource(await file.text());}}/></label><details className="mt-4"><summary className="cursor-pointer text-xs text-muted-foreground">View or edit CV source</summary><Textarea aria-label="Original CV source" className="mt-3 min-h-64 font-mono text-xs" value={source} onChange={e=>setSource(e.target.value)}/></details><div className="mt-5 flex justify-end"><Button variant="outline" disabled={busy} onClick={()=>save(()=>put("/settings/cv",{source}),"Original CV saved. Existing workflows keep their previous copy.")}><Save/>Save original CV</Button></div></Card>
    <Card className="p-6"><h2 className="flex items-center gap-2 text-sm font-semibold"><Mail size={16} className="text-primary"/>Gmail & response tracking</h2><div className="my-5 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-muted/60 p-4"><div><p className="text-xs font-medium">{data.gmail_connecting ? "Complete Google consent in the browser" : data.gmail_saved ? "Gmail connection saved" : "Connect your Gmail account"}</p><p className="mt-1.5 text-[11px] text-muted-foreground">Send reviewed applications and check for recruiter replies.</p></div><Button variant="outline" disabled={busy || data.gmail_connecting} onClick={()=>save(async()=>{await post("/settings/gmail/connect");setData({...data,gmail_connecting:true});},"Google consent opens on the computer running the backend.")}>{data.gmail_connecting ? "Connecting…" : data.gmail_saved ? "Reconnect Gmail" : "Connect Gmail"}</Button></div><ErrorNotice message={data.inbox.error}/><label className="flex items-center gap-3 text-xs font-medium"><input type="checkbox" checked={data.inbox.enabled} onChange={e=>setData({...data,inbox:{...data.inbox,enabled:e.target.checked}})}/>Automatically check for recruiter responses</label><p className="mb-5 ml-6 mt-2 text-[11px] leading-5 text-muted-foreground">While the backend is running, clear interview invitations and rejections update the tracker. Other replies stay available for your review.</p><div className="flex flex-wrap items-end justify-between gap-4"><label className="text-xs text-muted-foreground">Check every (minutes)<Input className="mt-2 w-32" type="number" min={1} max={1440} value={data.inbox.interval_minutes} onChange={e=>setData({...data,inbox:{...data.inbox,interval_minutes:Number(e.target.value)}})}/></label><Button variant="outline" disabled={busy} onClick={()=>save(()=>put("/settings/inbox",{enabled:data.inbox.enabled,interval_minutes:data.inbox.interval_minutes}),"Inbox preferences saved.")}><Save/>Save preferences</Button></div>{data.inbox.last_checked && <p className="mt-4 text-[10px] text-muted-foreground">Last checked: {new Date(data.inbox.last_checked*1000).toLocaleString()}</p>}</Card></div></div>;
}
function ListField({label,values,onChange}: {label:string;values:string[];onChange:(values:string[])=>void}) {return <label className="text-xs font-medium">{label}<span className="ml-1 font-normal text-muted-foreground">(comma separated)</span><Input className="mt-2" value={values.join(",")} onChange={e=>onChange(e.target.value.split(","))}/></label>;}
