import { ArrowRight, BriefcaseBusiness, LoaderCircle } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function PageHeading({eyebrow, title, description, children}: {eyebrow?: string; title: string; description: string; children?: React.ReactNode}) { return <div className="mb-8 flex flex-wrap items-center justify-between gap-4"><div>{eyebrow && <p className="mb-2 text-[10px] font-semibold uppercase tracking-[.17em] text-primary">{eyebrow}</p>}<h1 className="text-[28px] font-semibold tracking-[-.035em]">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div>{children}</div>; }
export function Empty({title, description, action = true}: {title: string; description: string; action?: boolean}) { return <div className="flex flex-col items-center px-6 py-16 text-center"><span className="mb-4 flex size-12 items-center justify-center rounded-xl border bg-muted"><BriefcaseBusiness className="text-muted-foreground" size={22}/></span><h3 className="font-medium">{title}</h3><p className="mt-2 max-w-sm text-sm leading-relaxed text-muted-foreground">{description}</p>{action && <Button asChild variant="outline" className="mt-6"><Link href="/workflow">Start a workflow<ArrowRight/></Link></Button>}</div>; }
export function Loading({text = "Loading your workspace…"}: {text?: string}) { return <div role="status" className="flex items-center justify-center gap-3 py-16 text-sm text-muted-foreground"><LoaderCircle size={18} className="animate-spin"/>{text}</div>; }
export function ErrorNotice({message}: {message?: string | null}) { return message ? <div role="alert" className="mb-5 whitespace-pre-wrap rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{message}</div> : null; }
export function StatusBadge({status}: {status: string}) { const labels: Record<string,string> = {applied: "Applied", interview: "Interview", offer: "Offer", rejected: "Rejected", responded: "Responded", found: "Saved", shortlisted: "In progress", delivery_failed: "Delivery failed"}; return <span className={cn("inline-flex items-center gap-1.5 rounded-md px-2 py-1 text-[11px] font-medium", status === "interview" ? "bg-purple-50 text-purple-700" : status === "offer" ? "bg-emerald-50 text-emerald-700" : status === "rejected" || status === "delivery_failed" ? "bg-rose-50 text-rose-700" : "bg-slate-100 text-slate-600")}><span className="size-1.5 rounded-full bg-current opacity-70"/>{labels[status] || status}</span>; }
export function CompanyMark({name}: {name: string}) { return <span className="flex size-10 shrink-0 items-center justify-center rounded-lg border bg-[#f6f5fa] text-sm font-semibold text-[#76688c]">{name.slice(0,2).toUpperCase()}</span>; }
