"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, CheckCheck, ChevronRight, ExternalLink, FileText, LoaderCircle, MapPin, Paperclip, Search, Send, ShieldCheck, Sparkles } from "lucide-react";
import { api, patch, plainText, post, safeUrl, steps, stepIndex, type Draft, type Job, type Settings, type Workflow } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { CompanyMark, Empty, ErrorNotice, Loading, PageHeading } from "@/components/shared";
import { CVReview } from "@/components/cv-review";
import { cn } from "@/lib/utils";

function Stepper({step}: {step: number}) { return <div className="mb-8 flex overflow-x-auto rounded-xl border bg-muted/40 px-5 py-5">{steps.map((label,index) => <div key={label} className="flex min-w-max flex-1 items-center"><div aria-current={index === step ? "step" : undefined} className="flex items-center gap-2.5"><span className={cn("flex size-6 items-center justify-center rounded-full border text-[10px] font-semibold", index < step ? "border-primary/15 bg-secondary text-primary" : index === step ? "border-primary bg-primary text-white" : "bg-white text-muted-foreground")}>{index < step ? <Check size={13}/> : index+1}</span><span className={cn("text-xs", index === step ? "font-semibold text-foreground" : "text-muted-foreground")}>{label}</span></div>{index < 4 && <ChevronRight size={14} className="mx-4 shrink-0 text-border"/>}</div>)}</div>; }

export function NewWorkflow() {
  const router = useRouter();
  const [query,setQuery] = useState(""); const [location,setLocation] = useState("Morocco");
  const [country,setCountry] = useState("MA"); const [date,setDate] = useState("");
  const [limit,setLimit] = useState(5); const [score,setScore] = useState(30);
  const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  useEffect(() => { api<Settings>("/settings").then(data => {setQuery(data.profile.target_roles[0] || ""); setLocation(data.profile.preferred_locations[0] || "Morocco");}).catch(e => setError(e.message)); }, []);
  return <div className="fade-in"><PageHeading eyebrow="One opportunity at a time" title="Your next chapter starts here" description="Find a role, make it yours, and send an application you feel good about."/><Stepper step={0}/><ErrorNotice message={error}/><div className="grid gap-7 xl:grid-cols-[1fr_300px]"><Card className="p-7 sm:p-8"><div className="mb-7 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-lg bg-secondary text-primary"><Search size={20}/></span><div><h2 className="text-lg font-semibold tracking-tight">Find your next opportunity</h2><p className="mt-1 text-xs text-muted-foreground">A focused search, matched to your experience.</p></div></div><form onSubmit={async e => {e.preventDefault();setBusy(true);setError("");try {const flow = await post<Workflow>("/workflows", {query,location,country,post_date:date || null,limit_per_source:limit,minimum_score:score});router.push(`/workflow/${flow.id}`);} catch(e) {setError((e as Error).message);setBusy(false);}}}>
      <div className="space-y-5"><label className="block text-xs font-medium">Job title or keywords<Input className="mt-2" placeholder="e.g. Data Engineer" value={query} onChange={e => setQuery(e.target.value)} required minLength={2}/></label><div className="grid gap-5 sm:grid-cols-[1fr_100px]"><label className="text-xs font-medium">Location<Input className="mt-2" value={location} onChange={e => setLocation(e.target.value)} placeholder="City or country"/></label><label className="text-xs font-medium">Country code<Input className="mt-2 uppercase" value={country} onChange={e => setCountry(e.target.value.toUpperCase())} maxLength={2} minLength={2} required/></label></div><label className="block text-xs font-medium">Published on or after <span className="font-normal text-muted-foreground">(optional)</span><Input type="date" className="mt-2 max-w-xs" value={date} onChange={e => setDate(e.target.value)}/><span className="mt-2 block text-[11px] font-normal text-muted-foreground">Includes this day and every day after it.</span></label><details className="rounded-lg border px-4 py-3"><summary className="cursor-pointer text-xs text-muted-foreground">Search preferences</summary><div className="mt-4 grid grid-cols-2 gap-4"><label className="text-xs">Results per source<Input className="mt-2" type="number" min={1} max={20} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><label className="text-xs">Minimum match score<Input className="mt-2" type="number" min={0} max={100} value={score} onChange={e=>setScore(Number(e.target.value))}/></label></div></details></div><div className="mt-8 flex items-center justify-between border-t pt-6"><span className="flex items-center gap-1.5 text-[11px] text-muted-foreground"><ShieldCheck size={14}/>You review every step</span><Button type="submit" disabled={busy}>{busy ? <LoaderCircle className="animate-spin"/> : <Search/>}Search jobs<ArrowRight/></Button></div>
    </form></Card><div><div className="rounded-xl bg-[#f8f7fb] p-6"><Sparkles className="mb-4 text-primary" size={22}/><h3 className="text-sm font-semibold">Less busywork. More possibility.</h3><p className="mt-3 text-xs leading-6 text-muted-foreground">CareerAI searches your connected sources and ranks opportunities against your profile. You choose what comes next.</p><div className="mt-5 space-y-3 border-t pt-5">{["Jobs matched to your skills", "A CV tailored with your approval", "Every application in one place"].map(t=><p key={t} className="flex gap-2 text-xs text-muted-foreground"><Check size={14} className="text-primary"/>{t}</p>)}</div></div><p className="mt-5 px-2 text-[11px] leading-5 text-muted-foreground">Searching LinkedIn, ReKrute, Dreamjob, Remotive, and Tavily. Availability depends on your configured sources.</p></div></div></div>;
}

export function WorkflowScreen({id}: {id: string}) {
  const [flow,setFlow] = useState<Workflow | null>(null); const [draft,setDraft] = useState<Draft>({});
  const [error,setError] = useState(""); const [saving,setSaving] = useState(false); const [busy,setBusy] = useState(false); const [confirmed,setConfirmed] = useState(false);
  const current = useRef<Workflow | null>(null); const currentDraft = useRef<Draft>({}); const queue = useRef<Promise<void>>(Promise.resolve()); const pending = useRef(0); const saveError = useRef(false);
  const accept = useCallback((value: Workflow, resetDraft = false) => {current.current=value;setFlow(value);if(resetDraft){currentDraft.current=value.draft;setDraft(value.draft);}}, []);
  useEffect(() => { api<Workflow>(`/workflows/${id}`).then(value=>accept(value,true)).catch(e=>setError(e.message)); }, [id,accept]);
  useEffect(() => {if(flow?.status !== "running") return; const timer=setInterval(()=>{api<Workflow>(`/workflows/${id}`).then(value=>accept(value,true)).catch(e=>setError(e.message));},2500); return ()=>clearInterval(timer);}, [flow?.status,id,accept]);
  const edit = (changes: Partial<Draft>) => {
    currentDraft.current={...currentDraft.current,...changes};setDraft(currentDraft.current);setSaving(true);pending.current++;
    queue.current=queue.current.then(async()=>{try {if(saveError.current)throw new Error("Refresh this workflow before editing again; some changes could not be saved.");const value=await patch<Workflow>(`/workflows/${id}/draft`,{revision:current.current!.revision,...changes});accept(value);}catch(e){setError((e as Error).message);saveError.current=true;}finally{pending.current--;if(!pending.current)setSaving(false);}});
  };
  const act = async(action: string, approved = false) => {setBusy(true);setError("");await queue.current; if(saveError.current){setError("Some edits could not be saved. Refresh this workflow before continuing.");setBusy(false);return;}try {accept(await post<Workflow>(`/workflows/${id}/actions/${action}`,{revision:current.current!.revision,approved}),true);setConfirmed(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(!flow) return <><ErrorNotice message={error}/>{!error && <Loading/>}</>;
  const job=flow.selected_job; const index=stepIndex(flow.step); const isEmail=flow.contact?.method === "email"; const processing=flow.status === "running";
  const titles=["Finding your next opportunity", "A good fit starts here", "Make your experience count", "A considered first impression", "Ready for your next step?", "Application submitted"];
  const descriptions=["Searching your sources and ranking matches against your profile.","Choose an opportunity to build your application around.","Review each suggestion. Keep your voice and the facts that matter.","Give your application a personal final touch.","Review the details below before you submit.","Your application is now in the tracker. We'll help you follow what comes next."];
  return <div className="fade-in"><PageHeading eyebrow={job ? `${job.company} / ${job.title}` : "Your application workflow"} title={titles[index]} description={descriptions[index]}><Link href="/applications" className="flex items-center gap-1.5 text-xs text-muted-foreground"><CheckCheck size={15}/>{saving ? "Saving edits…" : "Saved to Applications"}</Link></PageHeading><Stepper step={index}/><ErrorNotice message={error || flow.error}/>
    {processing ? <Card><Loading text={flow.last_action === "search" ? "Searching and ranking jobs. This can take a few minutes…" : flow.last_action === "select" ? "Reviewing the opportunity and preparing CV suggestions…" : flow.last_action === "tailor" ? "Compiling your CV and preparing the application…" : "Submitting your reviewed application…"}/><p className="mb-8 text-center text-xs text-muted-foreground">You can leave this page and continue from Applications.</p></Card> : <>
    {flow.step === "search" && <Button onClick={()=>act("search")} disabled={busy}>Retry search<ArrowRight/></Button>}
    {flow.step === "job_review" && (flow.jobs.length ? <><div className="mb-4 flex items-center justify-between"><p className="text-xs text-muted-foreground">{flow.jobs.length} opportunities · ranked for you</p><Button asChild variant="ghost" size="sm"><Link href="/workflow">New search</Link></Button></div><div className="space-y-3">{flow.jobs.map((job,i)=><JobCard key={job.url} job={job} selected={draft.selected_index === i} onSelect={()=>edit({selected_index:i})}/>)}</div><Footer saving={saving}><Button onClick={()=>act("select")} disabled={busy || draft.selected_index === undefined}>Tailor my CV<ArrowRight/></Button></Footer></> : <Card><Empty title="No matches this time" description={flow.no_jobs_message || "Try a broader role, another location, or an earlier date."} action={false}/><div className="mb-8 flex justify-center"><Button asChild><Link href="/workflow">Adjust search<ArrowRight/></Link></Button></div></Card>)}
    {flow.step === "cv_tailoring" && <><CVReview flow={flow} draft={draft} edit={edit}/><Footer saving={saving}><Button onClick={()=>act("tailor")} disabled={busy}>Approve CV & continue<ArrowRight/></Button></Footer></>}
    {(flow.step === "email_review" || flow.step === "send") && <div className="grid gap-6 xl:grid-cols-[1fr_290px]"><Card className="overflow-hidden"><div className="border-b px-6 py-4 text-sm font-medium">{isEmail ? "Application email" : "Application method"}</div><div className="p-6">{isEmail ? flow.step === "email_review" ? <div className="space-y-5"><label className="block text-xs text-muted-foreground">To<Input type="email" aria-label="Recipient" className="mt-2" value={draft.recipient || ""} onChange={e=>edit({recipient:e.target.value})}/></label><label className="block text-xs text-muted-foreground">Subject<Input aria-label="Subject" className="mt-2" value={draft.subject || ""} onChange={e=>edit({subject:e.target.value})}/></label><label className="block text-xs text-muted-foreground">Message<Textarea aria-label="Email message" className="mt-2 min-h-72 leading-7" value={draft.body || ""} onChange={e=>edit({body:e.target.value})}/></label></div> : <><p className="text-xs text-muted-foreground">To <span className="ml-2 text-foreground">{draft.recipient}</span></p><h3 className="mb-6 mt-4 text-sm font-semibold">{draft.subject}</h3><p className="whitespace-pre-wrap text-sm leading-7">{draft.body}</p></> : <><span className="mb-4 inline-block rounded-lg bg-secondary px-3 py-1.5 text-xs text-primary">{flow.contact?.method === "easy_apply" ? "LinkedIn Easy Apply" : flow.contact?.method === "linkedin" ? "LinkedIn application" : "External application"}</span><p className="text-sm leading-7 text-muted-foreground">{safeUrl(flow.contact?.application_url) ? "This role accepts applications on its website. Download your tailored CV and complete the form there, then confirm submission here to start tracking." : "No application contact was found. Open the original job post to check the instructions, then confirm here after applying."}</p><Button asChild variant="outline" className="mt-6"><a href={safeUrl(flow.contact?.application_url) || safeUrl(job?.url)} target="_blank" rel="noreferrer">Open application page<ExternalLink/></a></Button></>}
      <div className="mt-7 flex items-center justify-between rounded-lg border bg-muted/40 p-3"><div className="flex items-center gap-3"><Paperclip size={17} className="text-primary"/><div><p className="text-xs font-medium">tailored-cv.pdf</p><p className="mt-1 text-[10px] text-muted-foreground">{isEmail ? "Attached to this application" : "Ready to download"}</p></div></div><a className="text-xs font-medium text-primary" href={`/api/workflows/${id}/cv.pdf`} target="_blank" rel="noreferrer">Review PDF ↗</a></div></div></Card><div><Card className="p-5"><CompanyMark name={job?.company || "Job"}/><h3 className="mt-4 text-sm font-semibold">{job?.title}</h3><p className="mt-1 text-xs text-muted-foreground">{job?.company}</p><p className="mt-3 flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin size={13}/>{job?.location || "Location unspecified"}</p><div className="mt-5 border-t pt-4 text-xs leading-6 text-muted-foreground"><p className="flex items-center gap-2"><Check className="text-green-600" size={13}/>CV reviewed and prepared</p><p className="flex items-center gap-2"><FileText className="text-primary" size={13}/>Application saved</p></div></Card>{flow.step === "send" && <div className="mt-5 rounded-xl bg-secondary/60 p-5"><label className="flex cursor-pointer items-start gap-3 text-xs leading-6"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{isEmail ? "I have reviewed the recipient, email and attached CV, and approve sending this application." : "I have completed and submitted this application on the application website."}</label><Button className="mt-5 w-full" onClick={()=>act(isEmail ? "send" : "manual",true)} disabled={!confirmed || busy}><Send/>{isEmail ? "Send application" : "Mark as applied"}</Button></div>}</div></div>}
    {flow.step === "email_review" && <Footer saving={saving}><Button onClick={()=>act("review")} disabled={busy}>Continue to final review<ArrowRight/></Button></Footer>}
    {flow.step === "send" && <Button variant="ghost" className="mt-6" onClick={()=>act("back")} disabled={busy}><ArrowLeft/>Back to review</Button>}
    {flow.step === "submitted" && <Card className="px-6 py-14 text-center"><span className="mx-auto mb-5 flex size-14 items-center justify-center rounded-full bg-green-50 text-green-600"><CheckCheck size={26}/></span><h2 className="text-xl font-semibold">One step closer.</h2><p className="mt-3 text-sm text-muted-foreground">Your application to {job?.company} has been recorded.</p><Button asChild className="mt-7"><Link href="/tracker">View application tracker<ArrowRight/></Link></Button></Card>}
    </>}
  </div>;
}
function Footer({saving,children}: {saving:boolean;children:React.ReactNode}) {return <div className="sticky bottom-0 mt-7 flex items-center justify-between gap-3 border-t bg-white/95 py-5 backdrop-blur"><span aria-live="polite" className="flex items-center gap-2 text-xs text-muted-foreground">{saving ? <LoaderCircle size={14} className="animate-spin"/> : <CheckCheck size={14}/>} {saving ? "Saving changes…" : "All changes saved"}</span>{children}</div>;}
function JobCard({job,selected,onSelect}: {job:Job;selected:boolean;onSelect:()=>void}) {return <Card className={cn("transition-colors",selected && "border-primary/50 bg-[#fbfaff] ring-1 ring-primary/15")}><label className="flex cursor-pointer items-start gap-4 p-5"><input className="mt-3" type="radio" name="job" checked={selected} onChange={onSelect} aria-label={`Select ${job.title} at ${job.company}`}/><CompanyMark name={job.company}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{job.title}</h3>{job.match_score !== undefined && job.match_score !== null && <span className="rounded-md bg-green-50 px-2 py-1 text-[11px] font-medium text-green-700">{Math.round(job.match_score)}% match</span>}</div><p className="mt-1 text-xs text-muted-foreground">{job.company} <span className="mx-1">·</span> {job.location || "Location unspecified"}</p><div className="mt-3 flex flex-wrap gap-2">{job.match_reasons?.slice(0,2).map(reason=><span key={reason} className="text-xs leading-5 text-muted-foreground">{reason}</span>)}</div><p className="mt-3 text-[10px] uppercase tracking-wider text-muted-foreground">{job.source}</p></div></label><details className="border-t px-5 py-3"><summary className="cursor-pointer text-xs text-muted-foreground">View job details</summary><p className="mt-4 max-h-64 overflow-y-auto whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{plainText(job.description) || job.requirements?.join("\n") || "Read the original listing for full details."}</p>{safeUrl(job.url) && <a className="mt-4 inline-flex items-center gap-1 text-xs text-primary" href={safeUrl(job.url)} target="_blank" rel="noreferrer">Original listing<ExternalLink size={12}/></a>}</details></Card>;}
